In [49]:
import warnings
from sklearn.exceptions import UndefinedMetricWarning
from sklearn.metrics import classification_report, confusion_matrix

# Before calling metrics functions, suppress the warning
warnings.filterwarnings('ignore', category=UndefinedMetricWarning)

# # Now you can call classification_report and confusion_matrix without seeing the warning
# print(classification_report(y_test_class, y_pred_class))
# print(confusion_matrix(y_test_class, y_pred_class))


In [50]:
import pandas as pd
import io


In [51]:
data = pd.read_csv("https://raw.githubusercontent.com/gnaneshwari1802/EDA-Bank-Loan-Default-Risk-Analysis/main/Training%20Data.csv/Training%20Data.csv")
data.head()

Id   Income  Age  Experience Married/Single House_Ownership Car_Ownership  \
0   1  1303834   23           3         single          rented            no   
1   2  7574516   40          10         single          rented            no   
2   3  3991815   66           4        married          rented            no   
3   4  6256451   41           2         single          rented           yes   
4   5  5768871   47          11         single          rented            no   

            Profession                 CITY           STATE  CURRENT_JOB_YRS  \
0  Mechanical_engineer                 Rewa  Madhya_Pradesh                3   
1   Software_Developer             Parbhani     Maharashtra                9   
2     Technical_writer            Alappuzha          Kerala                4   
3   Software_Developer          Bhubaneswar          Odisha                2   
4        Civil_servant  Tiruchirappalli[10]      Tamil_Nadu                3   

   CURRENT_HOUSE_YRS  Risk_Flag  
0                 13          0  
1                 13          0  
2                 10          0  
3                 12          1  
4                 14          1

In [52]:
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam
import pydot
import graphviz
from IPython.display import SVG
from keras.utils.vis_utils import model_to_dot
from keras.utils import plot_model
import seaborn as sns
import pandas as pd
import numpy as np

In [53]:
dataset=data.drop(columns=['Id'])

In [54]:
data.columns

Index(['Id', 'Income', 'Age', 'Experience', 'Married/Single',
       'House_Ownership', 'Car_Ownership', 'Profession', 'CITY', 'STATE',
       'CURRENT_JOB_YRS', 'CURRENT_HOUSE_YRS', 'Risk_Flag'],
      dtype='object')

In [55]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
import category_encoders as ce

label_encoder = LabelEncoder()
for col in ['Married/Single', 'Car_Ownership']:
    data[col] = label_encoder.fit_transform(data[col])

onehot_encoder = OneHotEncoder()
data['House_Ownership'] = onehot_encoder.fit_transform(data['House_Ownership'].values.reshape(-1, 1)).toarray()

high_card_features = ['Profession', 'CITY', 'STATE']
count_encoder = ce.CountEncoder()

# Transform the features, rename the columns with the _count suffix, and join to dataframe
count_encoded = count_encoder.fit_transform(data[high_card_features])
data = data.join(count_encoded.add_suffix("_count"))

data = data.drop(labels=['Profession', 'CITY', 'STATE'], axis=1)

In [56]:
x = data.drop("Risk_Flag", axis=1)
y = data["Risk_Flag"]
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, stratify = y, random_state = 2)

In [57]:
# Convert data to NumPy arrays if they are not already
x_train = np.array(x_train)
y_train = np.array(y_train)


In [58]:
model= Sequential()
model1= Sequential()
model.add(Dense(4,input_shape=(12,), activation='relu'))

model.add(Dense(2, activation='sigmoid'))


model1.add(Dense(4,input_shape=(12,), activation='relu'))

model1.add(Dense(2, activation='sigmoid'))


In [59]:

model.compile(optimizer="Adam", loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [65]:
model1.compile(optimizer="rmsprop", loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [61]:
x_train

array([[2.638500e+04, 7.213058e+06, 5.000000e+01, ..., 4.661000e+03,
        7.600000e+02, 2.556200e+04],
       [1.367600e+04, 4.313468e+06, 3.500000e+01, ..., 4.668000e+03,
        8.220000e+02, 2.529700e+04],
       [1.166780e+05, 3.791460e+06, 2.200000e+01, ..., 5.127000e+03,
        9.700000e+02, 2.840000e+04],
       ...,
       [1.997650e+05, 3.991815e+06, 6.600000e+01, ..., 5.195000e+03,
        6.880000e+02, 5.805000e+03],
       [1.059750e+05, 2.577341e+06, 4.800000e+01, ..., 5.053000e+03,
        8.850000e+02, 7.890000e+03],
       [1.561220e+05, 1.154849e+06, 5.800000e+01, ..., 4.944000e+03,
        5.960000e+02, 5.490000e+03]])

In [62]:
model.fit(x_train, y_train, batch_size=10, epochs=5)


Epoch 1/5
20160/20160 [==============================] - 74s 4ms/step - loss: 2794.7742 - accuracy: 0.7826
Epoch 2/5
20160/20160 [==============================] - 67s 3ms/step - loss: 0.3882 - accuracy: 0.8757
Epoch 3/5
20160/20160 [==============================] - 72s 4ms/step - loss: 0.3729 - accuracy: 0.8770
Epoch 4/5
20160/20160 [==============================] - 70s 3ms/step - loss: 0.3729 - accuracy: 0.8770
Epoch 5/5
20160/20160 [==============================] - 66s 3ms/step - loss: 0.3729 - accuracy: 0.8770


In [63]:
# model1.compile(optimizer="rmsprop", loss='categorical_crossentropy', metrics=['accuracy'])

In [66]:
model1.fit(x_train, y_train, batch_size=10, epochs=5)


Epoch 1/5
20160/20160 [==============================] - 67s 3ms/step - loss: 2469.1809 - accuracy: 0.7726
Epoch 2/5
20160/20160 [==============================] - 71s 4ms/step - loss: 1186.8691 - accuracy: 0.7704
Epoch 3/5
20160/20160 [==============================] - 71s 4ms/step - loss: 888.2753 - accuracy: 0.7700
Epoch 4/5
20160/20160 [==============================] - 57s 3ms/step - loss: 379.5999 - accuracy: 0.7842
Epoch 5/5
20160/20160 [==============================] - 58s 3ms/step - loss: 0.3889 - accuracy: 0.8770


In [68]:
# Obtain predicted class labels using your trained model and testing input features
y_pred = model.predict(x_test)

1575/1575 [==============================] - 5s 3ms/step


In [72]:
y_pred

array([[0.7268431 , 0.27315682],
       [0.7268431 , 0.27315682],
       [0.7268431 , 0.27315682],
       ...,
       [0.7268431 , 0.27315682],
       [0.7268431 , 0.27315682],
       [0.7268431 , 0.27315682]], dtype=float32)

In [74]:
y_pred.shape

(50400, 2)

In [75]:
import numpy as np

# Convert probabilities to binary labels using a threshold of 0.5
y_pred_binary = np.where(y_pred[:, 1] > 0.5, 1, 0)

# Now you can use y_test and y_pred_binary to compute classification report and confusion matrix
print(classification_report(y_test, y_pred_binary))
print(confusion_matrix(y_test, y_pred_binary))


              precision    recall  f1-score   support

           0       0.88      1.00      0.93     44201
           1       0.00      0.00      0.00      6199

    accuracy                           0.88     50400
   macro avg       0.44      0.50      0.47     50400
weighted avg       0.77      0.88      0.82     50400

[[44201     0]
 [ 6199     0]]


In [76]:
y_pred_binary

array([0, 0, 0, ..., 0, 0, 0])

In [79]:
np.unique(y_pred_binary)

array([0])

In [71]:
y_test

90388     0
44883     0
74955     0
109598    1
176932    1
         ..
158023    0
179235    0
115032    0
17450     0
55608     0
Name: Risk_Flag, Length: 50400, dtype: int64

In [80]:
# from sklearn.metrics import classification_report,confusion_matrix
# print(classification_report(y_test,y_pred))
# print(confusion_matrix(y_test,y_pred))

In [81]:
model.evaluate(x_test, y_test)

1575/1575 [==============================] - 5s 3ms/step - loss: 0.3729 - accuracy: 0.8770


[0.37285560369491577, 0.8770039677619934]

In [83]:
model1.evaluate(x_test, y_test)

1575/1575 [==============================] - 5s 3ms/step - loss: 0.3761 - accuracy: 0.8770


[0.37610262632369995, 0.876964271068573]